GET http://localhost:5000/subscribers

###

GET http://localhost:5000/subscribers/5fa687c84427416fb55e5fdb


### 
POST http://localhost:5000/subscribers
Content-Type: application/json

{
  "name": "Amazing person",
  "subscribedToChannel": "Web Dev Simplified"
}

###
DELETE http://localhost:5000/subscribers/5fa687c84427416fb55e5fda

###
PATCH http://localhost:5000/subscribers/5fa687c84427416fb55e5fdb
Content-Type: application/json

{
  "name": "New Name"
}